"use client";
import {useEffect,useMemo,useState} from "react";import {useParams,useRouter} from "next/navigation";import {Flag,ChevronLeft,ChevronRight,Send,Clock3} from "lucide-react";
export default function TestPage(){const p=useParams();const r=useRouter();const [test,setTest]=useState<any>();const [qs,setQs]=useState<any[]>([]);const [attempt,setAttempt]=useState<any>();const [answers,setAnswers]=useState<Record<string,string[]>>({});const [marked,setMarked]=useState<Record<string,boolean>>({});const [idx,setIdx]=useState(0);const [seconds,setSeconds]=useState(0);const [error,setError]=useState('');const [submitting,setSubmitting]=useState(false);
useEffect(()=>{async function load(){const [tRes,sRes]=await Promise.all([fetch(`/api/tests/${p.id}`),fetch(`/api/tests/${p.id}/start`,{method:'POST'})]);const t=await tRes.json(),s=await sRes.json();if(!tRes.ok||!sRes.ok){setError(t.error||s.error||'Unable to open test');return}setTest(t.test);setQs(t.questions);setAttempt(s);setSeconds(Math.max(0,Math.floor((new Date(s.expiresAt).getTime()-Date.now())/1000)))}load()},[p.id]);
useEffect(()=>{if(!attempt||seconds<=0)return;const timer=setInterval(()=>setSeconds(x=>Math.max(0,x-1)),1000);return()=>clearInterval(timer)},[attempt,seconds]);
useEffect(()=>{if(attempt&&seconds===0&&!submitting)submit(true)},[seconds,attempt]);
const q=qs[idx];const selected=answers[String(q?.id)]||[];const time=useMemo(()=>`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`,[seconds]);
function choose(optionId:number){setAnswers(a=>{const key=String(q.id);if(q.questionType==='SCQ')return {...a,[key]:[String(optionId)]};const cur=a[key]||[];const v=String(optionId);return {...a,[key]:cur.includes(v)?cur.filter(x=>x!==v):[...cur,v]}})}
async function submit(auto=false){if(submitting)return;if(!auto&&!confirm('Are you sure you want to submit this test?'))return;setSubmitting(true);const res=await fetch(`/api/tests/${p.id}/submit`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({attemptId:attempt.attemptId,answers})});const d=await res.json();if(!res.ok){setError(d.error||'Submission failed');setSubmitting(false);return}sessionStorage.setItem(`aitts-result-${d.result.attemptId}`,JSON.stringify(d.result));r.push(`/results?attempt=${d.result.attemptId}`)}
if(error)return <main className="container main"><div className="card" style={{padding:30}}><h2>Unable to open test</h2><p className="muted">{error}</p><button className="btn btn-secondary" onClick={()=>r.push('/tests')}>Back to tests</button></div></main>;if(!test||!q)return <main className="container main"><div className="card" style={{padding:30}}>Loading test…</div></main>;
return <main className="container main"><div className="dashboard-head"><div><span className="pill">{test.subject}</span><h1>{test.title}</h1><p className="muted">Question {idx+1} of {qs.length}</p></div><div className="card" style={{padding:'10px 15px',display:'flex',gap:9,alignItems:'center'}}><Clock3 size={18}/><span className="timer">{time}</span></div></div><div className="test-shell" style={{marginTop:18}}><div className="card question-card"><div className="question-number">Q{idx+1} · {q.questionType}</div><div className="question-text">{q.questionText}</div>{q.options.map((o:any)=><label key={o.id} className={`option ${selected.includes(String(o.id))?'selected':''}`}><input type={q.questionType==='SCQ'?'radio':'checkbox'} name={`q-${q.id}`} checked={selected.includes(String(o.id))} onChange={()=>choose(o.id)}/><span><b>{String.fromCharCode(65+o.optionOrder-1)}.</b> {o.optionText}</span></label>)}<div style={{display:'flex',justifyContent:'space-between',gap:10,marginTop:25}}><button className="btn btn-secondary" disabled={idx===0} onClick={()=>setIdx(i=>i-1)}><ChevronLeft size={16}/>Previous</button>{idx<qs.length-1?<button className="btn btn-primary" onClick={()=>setIdx(i=>i+1)}>Next<ChevronRight size={16}/></button>:<button className="btn btn-primary" onClick={()=>submit()}><Send size={16}/>Submit</button>}</div></div><aside className="card" style={{padding:20,height:'fit-content'}}><div style={{display:'flex',justifyContent:'space-between'}}><b>Question palette</b><span className="muted">{Object.values(answers).filter(x=>x.length).length}/{qs.length}</span></div><div className="nav-grid">{qs.map((x,i)=><button key={x.id} className={`nav-q ${answers[String(x.id)]?.length?'answered':''} ${i===idx?'current':''}`} onClick={()=>setIdx(i)}>{i+1}</button>)}</div><button className="btn btn-secondary" style={{width:'100%',marginTop:15}} onClick={()=>setMarked(m=>({...m,[String(q.id)]:!m[String(q.id)]}))}><Flag size={16}/>{marked[String(q.id)]?'Unmark':'Mark for review'}</button><button className="btn btn-primary" style={{width:'100%',marginTop:9}} onClick={()=>submit()} disabled={submitting}>{submitting?'Submitting…':'Submit test'}</button><p className="footer-note">Answers are graded securely on the server after submission.</p></aside></div></main>}
